### PR TITLE
Updated HealthCheckFormula

### PR DESCRIPTION
**Pull request by kiawnna**
@nick-bair here is the new version. let me know if you want anything changed!

### CODE REVIEW

**Review by nick-bair — CHANGES_REQUESTED** [review]
Excellent work, couple of changes discussed via DM

**Comment by kiawnna** [comment]
@nick-bair Made the requested changes--check them out. Also, the image stream formula is in this PR (PR #4 above).

**Review by nick-bair — CHANGES_REQUESTED** [review]
@kiawnna healthCheck looks good save for cleaning up the sendEmail step (per our DM).

For the image streaming formula:
1. Should the name used in the upload query be stored in the config (constructQueriesAndHeaders)?  Wouldn't that mean every file that gets uploaded would have the same name in the destination system?
2. In constructQueriesAndHeaders, the call to done can be simplified `done({ downloadHeaders, uploadHeaders, downloadQuery, uploadQuery }); since the key == variable name where the value is stored.

**Comment by kiawnna** [comment]
@nick-bair I agree with both of the above for the image streaming. I changed the name to refer to the name it gets from the source, so the destination will have the same name. I also simplified the done(); in constructQueriesAndHeaders.

**Review by nick-bair — APPROVED** [review]

**Pull request merged**
